#!/bin/sh

## git-get-chagnes
# Suppose you are working on a local branch named kaaj-kortesi
# Somebody added their changes to a remote branch agaye-ache
# You need those changes on your local branch.
# So you stash-> switch branches -> pull from remote -> switch branches -> rebase -> apply stash
#

remote_branch=$1
current_branch=$(git rev-parse --abbrev-ref HEAD)

test -z "$remote_branch" && echo "Enter a remote branch to pull changes from..." 1>&2 && exit 1

echo "On branch $current_branch"
echo "Pulling from remote $remote_branch"

git stash
git checkout "$remote_branch"
git pull --rebase origin "$remote_branch"
git checkout "$current_branch"
git rebase "$remote_branch"
git stash apply

echo "$remote_branch changes added to $current_branch"
