#!/usr/bin/env zsh

# editor
export EDITOR="lvim"

# fastlane
export FASTLANE_SKIP_ACTION_SUMMARY=1
export FASTLANE_HIDE_PLUGINS_TABLE=1
export FASTLANE_SKIP_UPDATE_CHECK=1
export SNAPSHOT_SKIP_OPEN_SUMMARY=1
